apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-agent-helm.fullname" . }}-env
  labels:
    {{- include "hermes-agent-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
